import os

from .chat_configs import NUM_RETURNED_HITS


#####
# Agent Configs
#####

AGENT_RETRIEVAL_STATS = os.environ.get("AGENT_RETRIEVAL_STATS", False)
if AGENT_RETRIEVAL_STATS == "True":
    AGENT_RETRIEVAL_STATS = True
elif AGENT_RETRIEVAL_STATS:
    AGENT_RETRIEVAL_STATS = False

AGENT_MAX_QUERY_RETRIEVAL_RESULTS = os.environ.get(
    "AGENT_MAX_QUERY_RETRIEVAL_RESULTS", NUM_RETURNED_HITS
)

try:
    atmqrr = int(AGENT_MAX_QUERY_RETRIEVAL_RESULTS)
    AGENT_MAX_QUERY_RETRIEVAL_RESULTS = atmqrr
except ValueError:
    raise ValueError(
        f"MAX_AGENT_QUERY_RETRIEVAL_RESULTS must be an integer, got {AGENT_MAX_QUERY_RETRIEVAL_RESULTS}"
    )


# Reranking agent configs
AGENT_RERANKING_STATS = os.environ.get("AGENT_RERANKING_TEST", False)
if AGENT_RERANKING_STATS == "True":
    AGENT_RERANKING_STATS = True
elif AGENT_RERANKING_STATS:
    AGENT_RERANKING_STATS = False

AGENT_RERANKING_MAX_QUERY_RETRIEVAL_RESULTS = os.environ.get(
    "AGENT_RERANKING_MAX_QUERY_RETRIEVAL_RESULTS", NUM_RETURNED_HITS
)

try:
    atmqrr = int(AGENT_RERANKING_MAX_QUERY_RETRIEVAL_RESULTS)
    AGENT_RERANKING_MAX_QUERY_RETRIEVAL_RESULTS = atmqrr
except ValueError:
    raise ValueError(
        f"AGENT_RERANKING_MAX_QUERY_RETRIEVAL_RESULTS must be an integer, got {AGENT_RERANKING_MAX_QUERY_RETRIEVAL_RESULTS}"
    )
